gender = ["Male", "Male", "Male", "Male", "Male", "Female", "Female", "Other"]
characters = ["Hanzo", "Orisa", "Roadhog", "Lucio", "Sombra", "Soldier", "Symmetra", "Reinhardt", "McCree", "Brigitte",
              "D.Va", "Tracer", "Mercy", "Doomfist", "Genji", "Zarya", "Widowmaker", "Junkrat", "Orisa", "Reaper",
              "Pharah", "Winston", "Moira"]
c_type = ["Healer", "Tank", "Damage"]
modes = ["quick", "ctf", "ranked", "3vs3", "solo", "mayhem"]
language_names = [
        "Afrikaans",
        "Arabic",
        "Belarusian",
        "Bulgarian",
        "Bosnian",
        "Catalan",
        "Czech",
        "Danish",
        "German",
        "Greek",
        "English",
        "Spanish",
        "Estonian",
        "Finnish",
        "French",
        "Irish",
        "Hebrew",
        "Hindi",
        "Croatian",
        "Hungarian",
        "Armenian",
        "Indonesian",
        "Icelandic",
        "Italian",
        "Japanese",
        "Kuanyama",
        "Korean",
        "Ganda",
        "Lithuanian",
        "Latvian",
        "Malagasy",
        "Marshallese",
        "Macedonian",
        "Mongolian",
        "Maltese",
        "Dutch",
        "Norwegian",
        "Polish",
        "Portuguese",
        "Romanian",
        "Russian",
        "Slovenian",
        "Albanian",
        "Serbian",
        "Swedish",
        "Thai",
        "Turkish",
        "Ukrainian",
        "Vietnamese",
        "Yoruba",
        "Chinese",
    ]